#!/bin/sh

#
#    Copyright (c) 2010 Nest Labs, Inc.
#    All rights reserved.
#
#    Description:
#      This file implements a script to start/stop the timed execution
#      daemon, crond.
#

# Source common library
. /etc/init.d/functions

CROND=${USRSBINDIR}/crond

case "${1}" in

'start')
	echo_and_log "Timed execution daemon:\c"

	if $CHECK cron; then
	    ${KILLALL} crond
	    if test -x ${CROND}; then
		${CROND} `${CAT} ${CONFDIR}/crond.options 2> ${NULL}` &
		echo_and_log " crond\c"
	    fi
	fi

	echo_and_log "."
	;;

'stop')
	${KILLALL} crond
	;;

*)
	echo "Usage: ${0} <start | stop>"
	exit 1
	;;

esac
