#!/bin/sh
#
# Copyright (c) 2015 Nest Labs, Inc.
# All rights reserved.
#
# This document is the property of Nest. It is considered
# confidential and proprietary information.
#
# This document may not be reproduced or transmitted in any form,
# in whole or in part, without the express written permission of
# Nest.
#
# Description:
# This file implements the list of services to start on system
# start-up.
#
# Source common library
. /etc/init.d/functions
# Start system services
${INITDIR}/announce start
${INITDIR}/start
${INITDIR}/hwclock restore
${INITDIR}/sysctl start
${INITDIR}/udev start
${INITDIR}/mountfs start
${INITDIR}/timezone check
${INITDIR}/hostname start
${INITDIR}/syslog start
${INITDIR}/watchdog start
${INITDIR}/nlmetrics start
${INITDIR}/orderly_reboot start
${INITDIR}/dbus start
${INITDIR}/heartbeat start
${INITDIR}/nlsleep start
${INITDIR}/nlshutdown start
${INITDIR}/networking start
${INITDIR}/sshd start
${INITDIR}/nestlabs start
${INITDIR}/monit start
