#!/bin/sh
#
# Copyright (c) 2010-2014 Nest Labs, Inc.
# All rights reserved.
#
# Description:
# This file handles early user-space start-up initialization,
# including mounting of various required file systems.
#
# Source common library
. /etc/init.d/functions
MOUNTFLAGS='-n'
UTMPDB=${VARDIR}/run/utmp
# Mount the proc filesystem, since the correct functionality of many
# subsequent commands are dependent on it. Be sure to pass '-n' to
# mount so that we don't try to update /etc/mtab (which is just a
# symlink to /proc/mounts anyway).
if [ ! -e ${ROOTDIR}proc/mounts ]; then
    ${MOUNT} ${MOUNTFLAGS} -t proc proc ${ROOTDIR}proc
fi
# Make sure that the root file system is mounted for read/write
# access. Again, passing '-n' to mount. Also, specify the 'noatime'
# option so we don't write back every time a file is accessed and
# prematurely wear out nonvolatile storage.
${MOUNT} ${MOUNTFLAGS} -o remount,rw,noatime ${ROOTDIR}
# Clean-up utmp/wtmp databases
:> ${UTMPDB}
if getent group utmp > ${NULL} 2>&1
then
    chgrp utmp ${UTMPDB}
    chmod 0664 ${UTMPDB}
fi
