#!/bin/sh

#
#    Copyright (c) 2010 Nest Labs, Inc.
#    All rights reserved.
#
#    Description:
#      This file implements a script to start/stop the system logging
#      daemons.
#

# Source common library
. /etc/init.d/functions

KLOGD=${SBINDIR}/klogd
SYSLOGD=${SBINDIR}/syslogd

case "${1}" in

'start')
	echo_and_log "Log daemons:\c"

	if $CHECK syslog; then
	    ${KILLALL} syslogd
	    if test -x ${SYSLOGD}; then
		${SYSLOGD} `${CAT} ${CONFDIR}/syslogd.options 2> ${NULL}` &
		echo_and_log " syslogd\c"
	    fi

	    ${KILLALL} klogd
	    if test -x ${KLOGD}; then
		${KLOGD} `${CAT} ${CONFDIR}/klogd.options 2> ${NULL}` &
		echo_and_log " klogd\c"
	    fi
	fi

	echo_and_log "."
	;;

'stop')
	${KILLALL} syslogd
	${KILLALL} klogd
	;;

'restart')
	${0} stop
	${0} start
	;;

*)
	echo "Usage: ${0} <start | stop | restart>"
	exit 1
	;;

esac
