#!/bin/sh

#
#    Copyright (c) 2015 Nest Labs, Inc.
#    All rights reserved.
#
#    This document is the property of Nest. It is considered
#    confidential and proprietary information.
#
#    This document may not be reproduced or transmitted in any form,
#    in whole or in part, without the express written permission of
#    Nest.
#
#    Description:
#       This file invokes the program to check and repair sthe x-loader
#       partition for D1/D2

# Source common library
. /etc/init.d/functions

${NESTLABSSBINDIR}/nliplupdater /nestlabs/share/fw/x-loader/x-load.bin.ift
