#
#    Copyright (c) 2012-2013 Nest Labs, Inc.
#    All rights reserved.
#
#    Description:
#      This file is the module options file for the Texas Instrument
#      WL12xx Wireless LAN module.
#

# Decline 802.11n AMPDU BA requests
options wl12xx ba_allowed=0
options wl12xx suspend_rx_ba_activity=1
options wl12xx set_dynamic_ps_timeout=40
