#
#    Copyright (c) 2010-2011 Nest, Inc.
#    All rights reserved.
#
#    Description:
#      This file contains the settings for the WPAN Tunnel Driver
#

WPANInterfaceName wpan0
NCPSocketName "system:killall -9 spi-server 1>&2 ; /usr/sbin/spi-server -p - -s /dev/spidev2.0 -i /sys/devices/platform/diamond-zigbee/interrupt/value -r /sys/devices/platform/diamond-zigbee/reset#/value -w /sys/devices/platform/diamond-zigbee/wake/value -T 0x00"
EmberUseASH 0
TXPower -15
TXPowerMode 5 # Boost-mode enabled, Using Bidir Antenna Port for TX, External PA present on Bidir port
#CCAThreshold -70
NCPHardResetPath "/sys/devices/platform/diamond-zigbee/reset#/value"

com.nestlabs.internal:Legacy:Enabled true
com.nestlabs.internal:Legacy:PreferInterface true

com.silabs:NCPInitFlushTime 0.25 # SAPPHIRE-13490

ActiveWakeupMask 1  # Don't propagate self test, SAPPHIRE-8039 <https://jira.nestlabs.com/browse/SAPPHIRE-8039>
NCPTXPowerLimit -10 # To Protect WiFi FEM, SAPPHIRE-8431 <https://jira.nestlabs.com/browse/SAPPHIRE-8431>
SyslogMask "-info -debug" # Disallow info or debug messages by default <https://jira.nestlabs.com/browse/COM-606>

# EM35x firmware upgrade commands
FirmwareCheckCommand "/nestlabs/bin/zb-loader --is-update-required /usr/share/silabs/data/firmware/ip-modem-app.bin"
FirmwareUpgradeCommand "/nestlabs/bin/zb-loader --app-easyload /usr/share/silabs/data/firmware/ip-modem-app.bin"
AutoUpdateFirmware true
